# Generated by Django 4.2.1 on 2023-10-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='need_confirmation',
            field=models.IntegerField(choices=[(2, 'Требуется подтверждение на статус пользователя'), (1, 'Требуется подтверждение на статус админа'), (0, 'Подтверждён')], default=2),
        ),
    ]
